# Chapter 4 - NumPy Basics: Arrays and Vectorized Computation

Note: **4.4 File Input and Output with Arrays** is skipped as `pandas` is preferred for such operations

## 4.5 Linear Algebra

In [1]:
import numpy as np
from numpy.linalg import inv, det

To do matrix multiplying, use `np.dot(arr1, arr2)`. Executing `arr1 * arr2` will only perform element-wise multiplication

In [2]:
arr1 = np.random.randint(1,9,(2,2))
arr2 = np.random.randint(1,9,(2,2))
arr3 = np.random.randint(1,9,(2,3))

arr1 = np.array([[7, 8],
                 [8, 5]])

arr2 = np.array([[2, 1],
                 [3, 7]])

arr3 = np.array([[2, 3, 6],
                 [1, 4, 5]])

# arr1 * arr2 performs element-wise multiplication
display(arr1 * arr2)

# np.dot(arr1, arr2) will calculate the matrix product of 2 matrices
display(np.dot(arr1, arr2))

# note: no. of columns of arr1 and no. of rows of arr2 need to match 
# for the calculation to be valid
display(np.dot(arr2, arr3))

array([[14,  8],
       [24, 35]])

array([[38, 63],
       [31, 43]])

array([[ 5, 10, 17],
       [13, 37, 53]])

Use `np.linalg` has a set of matrix decompositions and things like inverse and determinant. Use `inv` to get the inverse of the matrix. Recall that $\mathbf{A}^{-1}\mathbf A = \mathbf{I}$ for any square matrix $\mathbf{A}$. $\mathbf{I}$ is the identity matrix. This is a useful way to look at this function.

In [3]:
arr2 = np.array([[2, 1],
                 [3, 7]])
display(arr2)

# Use inv() to get the inverse of arr2
inv_arr2 = inv(arr2)
display(inv_arr2)

# Use the dot product to get the identity matrix
display(np.dot(arr2, inv(arr2)))

array([[2, 1],
       [3, 7]])

array([[ 0.63636364, -0.09090909],
       [-0.27272727,  0.18181818]])

array([[1.00000000e+00, 2.77555756e-17],
       [5.55111512e-17, 1.00000000e+00]])

In [4]:
arr2 = np.array([[2, 1],
                 [3, 7]])
display(arr2)

# Use inv() to get the inverse of arr2
inv_arr2 = inv(arr2)
display(inv_arr2)

# Use the dot product to get the identity matrix
display(np.dot(arr2, inv(arr2)))

array([[2, 1],
       [3, 7]])

array([[ 0.63636364, -0.09090909],
       [-0.27272727,  0.18181818]])

array([[1.00000000e+00, 2.77555756e-17],
       [5.55111512e-17, 1.00000000e+00]])

Other functions that are useful include `diag()` to get the diagonal of a square matrix, `det()` to find the determinant of the square matrix and `trace()` to get the sum of all elements in the main diagonal of a square matrix.

In [5]:
arr2 = np.array([[2, 1],
                 [3, 7]])

# Gets the diagonal of a square matrix
display(np.diag(arr2))

# Calculates the determinant of a square matrix
display(det(arr2))

# Gets the sum of all elements of the main diagonal of a square matrix
print(np.trace(arr2))

array([2, 7])

11.000000000000002

9


<hr>

**References:**

Python for Data Analysis, 2nd Edition, McKinney (2017)