# Chapter 4 - NumPy Basics: Arrays and Vectorized Computation

## 4.1 The NumPy ndarray: A Multidimensional Array Object

One of the key features of NumPy is its $N$-dimensional array object, or `ndarray`.

In [39]:
import numpy as np

<b>Declaring arrays</b>
1. Creating arrays with values
2. Creating arrays with all zeros
3. Creating arrays with all ones
4. Creating arrays with ranges

In [47]:
# Creating arrays with simple lists
list1 = [1, 3, 4, 7, 11] # 1 x 5
arr1 = np.array(list1)
print("arr1 = %s" % arr1)
print(type(arr1))
print('---')

list2 = [[2, 4], [12, 14], [22, 24]] # 3 x 2
arr2 = np.array(list2)
print("arr2 =")
print(arr2)
print(arr2.shape)

arr1 = [ 1  3  4  7 11]
<class 'numpy.ndarray'>
---
arr2 =
[[ 2  4]
 [12 14]
 [22 24]]
(3, 2)


In [48]:
# Creating arrays with zeros
arr1 = np.zeros(5)
print("arr1 = %s" % arr1)

arr2 = np.zeros((3,2))
print("arr2 =")
print(arr2)

arr1 = [0. 0. 0. 0. 0.]
arr2 =
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [49]:
# Creating arrays with ones
arr1b = np.ones(10)
print("arr1b = %s" % arr1b)
print('---')
arr2b = np.ones((3,2))
print("arr2b =")
print(arr2b)

arr1b = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
---
arr2b =
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [50]:
# Creating arrays with ranges
arr1 = np.arange(10)
print("arr1 = %s" % arr1)
print(type(arr1))
print(arr1 * 3)
print('---')
print()

arr2 = np.arange(10, 20)
print("arr2= %s" % arr2)
print(type(arr2))
print('---')
print()

arr3 = np.arange(10, 101, 10)
print("arr3= %s" % arr3)
print(type(arr3))

arr1 = [0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[ 0  3  6  9 12 15 18 21 24 27]
---

arr2= [10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
---

arr3= [ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


<b>Arrays Manipulation</b>
1. Changing datatypes of arrays
2. Addition & Subtraction
3. Multiplication & Division with a scalar
4. Boolean comparision

In [53]:
# Convert an array of floats to ints
arr1 = np.array([0.84837472, 0.06099506, 0.62602593, 0.05128479, 0.33769077])
print(arr1)
arr1 = arr1 * 100 # Multiply by 100 and then convert to int
print(arr1)
print(arr1.astype(int)) # Conver to int

[0.84837472 0.06099506 0.62602593 0.05128479 0.33769077]
[84.837472  6.099506 62.602593  5.128479 33.769077]
[84  6 62  5 33]


In [54]:
# Convert an array of str to float
arr2 = np.array(['0.60563224', '0.86530379', '0.51900541'])
print(arr2)
arr2 = arr2.astype(float)
arr2 = arr2*100
print(arr2)

['0.60563224' '0.86530379' '0.51900541']
[60.563224 86.530379 51.900541]


In [60]:
# Addition & Subtraction
arr1b = arr1[:3]
print(arr1b + arr2)
print('---')
print(arr2 - arr1b)

[145.400696  92.629885 114.503134]
---
[-24.274248  80.430873 -10.702052]


In [63]:
# Scalar multiplication
print(arr1b * 2)
print('---')
print(arr1b * 10.5)

[169.674944  12.199012 125.205186]
---
[890.793456   64.044813  657.3272265]


In [65]:
# Division of array / scalar
print(arr1b / 5)

# Divsion of scalar / array: This operation propogates the division to all elements in the array
print(5 / arr1b)

[16.9674944  1.2199012 12.5205186]
[0.05893622 0.81973852 0.0798689 ]


In [68]:
# Boolean comparisons - Returns an array with the same dimensions of the constituents
# and performs element-wise comparison for each value
print(arr1b)
print(arr2)
print(arr1b < arr2)

[84.837472  6.099506 62.602593]
[60.563224 86.530379 51.900541]
[False  True False]


<hr>

In [ ]:
print(a*2)

b = np.array([[3, 4, 5], [7, 9, 11]])
print(a+b)

In [ ]:
z1 = np.zeros(5)
print(z1)
z2 = np.zeros((6, 6))
print(z2)
print()

o1 = np.ones(3)
print(o1)
o2 = np.ones((4, 4))
print(o2)

In [ ]:
arr1 = np.random.randn(10)
print(arr1)

arr2 = np.random.randint(10, 20, 5)
print(arr2)

arr3 = np.random.ranf(5)
print(arr3)



**References:**

Python for Data Analysis, 2nd Edition, McKinney (2017)