# Chapter 4 - NumPy Basics: Arrays and Vectorized Computation

## 4.1 The NumPy ndarray: A Multidimensional Array Object

One of the key features of NumPy is its $N$-dimensional array object, or `ndarray`.

In [1]:
import numpy as np

### Declaring arrays

1. Creating arrays with `list`s

2. Creating arrays with all zeros using `np.zeros()`

3. Creating arrays with all ones using `np.ones()`

4. Creating arrays with ranges using `np.arange()`

**Creating arrays with `list`s**

In [2]:
# Creating arrays with lists
list1 = [1, 3, 4, 7, 11] # 1 x 5
arr1 = np.array(list1)
print("arr1 = %s" % arr1)
print(type(arr1))
print('---')

list2 = [[2, 4], [12, 14], [22, 24]] # 3 x 2
arr2 = np.array(list2)
print("arr2 =")
print(arr2)
print(arr2.shape)

arr1 = [ 1  3  4  7 11]
<class 'numpy.ndarray'>
---
arr2 =
[[ 2  4]
 [12 14]
 [22 24]]
(3, 2)


**Creating arrays with all zeros using `np.zeros()`**

In [3]:
# Creating arrays with np.zeros()
arr1 = np.zeros(5)
print("arr1 = %s" % arr1)

arr2 = np.zeros((3,2))
print("arr2 =")
print(arr2)

arr1 = [0. 0. 0. 0. 0.]
arr2 =
[[0. 0.]
 [0. 0.]
 [0. 0.]]


**Creating arrays with all ones using `np.ones()`**

In [4]:
# Creating arrays with np.ones()
arr1b = np.ones(10)
print("arr1b = %s" % arr1b)
print('---')
arr2b = np.ones((3,2))
print("arr2b =")
print(arr2b)

arr1b = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
---
arr2b =
[[1. 1.]
 [1. 1.]
 [1. 1.]]


**Creating arrays with ranges using `np.arange()`**

In [5]:
# Creating arrays with np.arange()
arr1 = np.arange(10)
print("arr1 = %s" % arr1)
print(type(arr1))
print(arr1 * 3)
print('---')
print()

arr2 = np.arange(10, 20)
print("arr2= %s" % arr2)
print('---')
print()

arr3 = np.arange(10, 101, 10)
print("arr3= %s" % arr3)

arr1 = [0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[ 0  3  6  9 12 15 18 21 24 27]
---

arr2= [10 11 12 13 14 15 16 17 18 19]
---

arr3= [ 10  20  30  40  50  60  70  80  90 100]


<hr>
### Manipulating arrays

1. Changing datatypes of arrays
2. Addition & Subtraction
3. Multiplication & Division with a scalar
4. Boolean comparision

**Changing datatypes of arrays**

In [6]:
# Convert an array of floats to ints
arr1 = np.array([0.84837472, 0.06099506, 0.62602593, 0.05128479, 0.33769077])
print(arr1)
arr1 = arr1 * 100 # Scalar multiplication: multiply by 100 
print(arr1)
print(arr1.astype(int)) # Convert to int

[0.84837472 0.06099506 0.62602593 0.05128479 0.33769077]
[84.837472  6.099506 62.602593  5.128479 33.769077]
[84  6 62  5 33]


In [7]:
# Convert an array of str to float
arr2 = np.array(['0.60563224', '0.86530379', '0.51900541'])
print(arr2)
arr2 = arr2.astype(float)
arr2 = arr2*100 # Scalar multiplication
print(arr2)

['0.60563224' '0.86530379' '0.51900541']
[60.563224 86.530379 51.900541]


**Addition & Subtraction**

In [8]:
# Addition & Subtraction
arr_x = np.array([[1, 3], 
                  [7, 5]])
arr_y = np.array([[2, 8], 
                  [16, 4]])
print(arr_x + arr_y) # Addition
print('---')
print(arr_x - arr_y) # Subtraction

[[ 3 11]
 [23  9]]
---
[[-1 -5]
 [-9  1]]


**Multiplication & Division with a scalar**

In [9]:
# Scalar multiplication
arr_b = np.array([[5, 15], 
                  [10, 20]])
print(arr_b * 2) # Multiply an array followed by a scalar
print('---')
print(10.5 * arr_b) # Multiply a scalar followed by an array

[[10 30]
 [20 40]]
---
[[ 52.5 157.5]
 [105.  210. ]]


In [10]:
# Division of array / scalar
arr_d = np.array([[20, 80], 
                  [160, 110],
                  [70, 220]])
print(arr_d / 20) # Division: array / scalar
print('---')
print(10 / arr_d) # Divsion: scalar / array - # this operation propogates the division to all elements in the array

[[ 1.   4. ]
 [ 8.   5.5]
 [ 3.5 11. ]]
---
[[0.5        0.125     ]
 [0.0625     0.09090909]
 [0.14285714 0.04545455]]


**Boolean comparision**

In [11]:
# Boolean comparisons
arr_t = np.array([[8, 4, 1],
                  [5, 7, 2]])
print(arr_t)
print()
arr_u = np.array([[17, -9, 11],
                  [17,  2, -9]])
print(arr_u)
print('---')
# Comparing arrays. Returns an array with the same dimensions of the constituents
# and performs element-wise comparison for each value
print(arr_t > arr_u)
print()
# Comparing arrays with a scalar Returns an array with the same dimensions of the array
# and performs element-wise comparison for each value witht the scalar
print(arr_u == 17)

[[8 4 1]
 [5 7 2]]

[[17 -9 11]
 [17  2 -9]]
---
[[False  True False]
 [False  True  True]]

[[ True False False]
 [ True False False]]


<hr>
### Basic Indexing and Slicing

1. Slicing a 1D array like a list
2. Slicing a 2D array
3. Slicing using Boolean arrays
4. Slicing using conditions (1 condition & multiple conditions)

**Slicing a 1D array like a list**

In [12]:
# Slicing a 1D array...like a list

arr_1d = np.arange(10, 20)
print(arr_1d)
print(arr_1d.shape)
# Slice an individual element
print(arr_1d[2])
print('---')

# Slice range from a 1D array
print(arr_1d[4:8])
print(arr_1d[:3])
print(arr_1d[6:])

[10 11 12 13 14 15 16 17 18 19]
(10,)
12
---
[14 15 16 17]
[10 11 12]
[16 17 18 19]


**Slicing a 2D array**

In [13]:
array_2d = np.array([[ 9,  1, 19, 13],
                     [ 5, 17,  8, 14],
                     [12, 18,  9, 13],
                     [20,  5,  5,  9]])

# Slice by taking 1 row & multiple rows
print(array_2d[2])
print()
print(array_2d[1:3])
print()
print(array_2d[2:])
print()

# Obtaining individual elements from a 2D array
print(array_2d[2][0]) # First value is row number, 2nd value is column number
print(array_2d[3,1])
print()

[12 18  9 13]

[[ 5 17  8 14]
 [12 18  9 13]]

[[12 18  9 13]
 [20  5  5  9]]

12
5



In [14]:
array_4by5 = np.array([[24, 24, 13, 30, 14],
                       [19, 49, 27, 13, 38],
                       [49, 12, 15, 37, 21],
                       [46,  6, 11, 36, 42],])

# Mixing it up: Slicing segments of an array
print(array_4by5[1, :3])
print()
print(array_4by5[2:, :3])
print()
print(array_4by5[1:, 1:4])

[19 49 27]

[[49 12 15]
 [46  6 11]]

[[49 27 13]
 [12 15 37]
 [ 6 11 36]]


**Slicing using Boolean arrays** and **Slicing using conditions (1 condition)**

In [15]:
array_3by4    = np.array([[3, 0, 1, 0],
                          [1, 3, 2, 2],
                          [1, 0, 2, 2]])

binaries_3by4 = np.array([1, 0, 1])

# Returns a True/False array with the same dimensions as the consituent
binaries_is_counted = binaries_3by4 == 1
print(binaries_is_counted)
print()
# Use the boolean array to filter for rows that satisfy the condition
print(array_3by4[binaries_is_counted])

[ True False  True]

[[3 0 1 0]
 [1 0 2 2]]


**Slicing using conditions (multiple conditions)**

In [16]:
array_6by2 = np.array([[ 6,  6],
                       [13,  7],
                       [10, 12],
                       [12,  7],
                       [11, 13],
                       [12, 10]])

# Forcing as a string to illustrate selection using OR logical operator
binaries_6 = np.array(['2', '0', '1', '1', '2', '0'])

# Returns a True/False array with the same dimensions as the consituent
binaries_is_positive = (binaries_6 == '1') | (binaries_6 == '2')
print(binaries_is_positive)
print()
# Use the boolean array to filter for rows that satisfy the condition
a_r1 = array_6by2[binaries_is_positive]
print(a_r1)
print()
# The following is equivalent
a_r2 = array_6by2[(binaries_6 == '1') | (binaries_6 == '2')]
print(a_r2)
print()
print(a_r1 == a_r2)

[ True False  True  True  True False]

[[ 6  6]
 [10 12]
 [12  7]
 [11 13]]

[[ 6  6]
 [10 12]
 [12  7]
 [11 13]]

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


<hr>
### Reshaping, Transposing Arrays, Swapping Axes

1. Use `.reshape()` to change the dimensions of an array

2. Using `.transpose()` and `.T` to swap axes

**Use `.reshape()` to change the dimensions of an array**

In [17]:
array_3by2 = np.array([[ 6,  6],
                       [13,  7],
                       [10, 12],])

# Use np.reshape() to change dimensions of an array
print(array_3by2.reshape(2, 3))
print()
print(array_3by2.reshape(1, 6))

[[ 6  6 13]
 [ 7 10 12]]

[[ 6  6 13  7 10 12]]


**Using `.transpose()` and `.T` to swap axes**

In [18]:
array_2by3 = np.array([[15, 18, 17],
                       [10,  1,  6]])

# Use transpose / T to swap axes of an array
print(array_2by3.transpose())
print()
print(array_2by3.T)

[[15 10]
 [18  1]
 [17  6]]

[[15 10]
 [18  1]
 [17  6]]


In [19]:
array_2by3 = np.random.randint(1,6,(2,3))
array_2by3

array([[2, 2, 3],
       [4, 3, 4]])

In [20]:
arr3 = np.array([[5, 2, 2],
                 [5, 3, 1]])
print(arr3.T)
print()
print(arr3)
print()
# Finding the matrix product of 2 matrices
print(np.dot(arr3.T,  arr3))

[[5 5]
 [2 3]
 [2 1]]

[[5 2 2]
 [5 3 1]]

[[50 25 15]
 [25 13  7]
 [15  7  5]]


<hr>

**References:**

Python for Data Analysis, 2nd Edition, McKinney (2017)