# Chapter 4 - NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

In [13]:
arr1 = np.arange(10)
print("arr1 = %s" % arr1)
print(type(arr1))
print(arr1 * 3)
print('---')
print()

arr2 = np.arange(10, 20)
print("arr2= %s" % arr2)
print(type(arr2))
print('---')
print()

arr3 = np.arange(10, 101, 10)
print("arr3= %s" % arr3)
print(type(arr3))

arr1 = [0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[ 0  3  6  9 12 15 18 21 24 27]
---

arr2= [10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
---

arr3= [ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


In [36]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [37]:
print(a*2)

b = np.array([[3, 4, 5], [7, 9, 11]])
print(a+b)

[[ 2  4  6]
 [ 8 10 12]]
[[ 4  6  8]
 [11 14 17]]


In [46]:
z1 = np.zeros(5)
print(z1)
z2 = np.zeros((6, 6))
print(z2)
print()

o1 = np.ones(3)
print(o1)
o2 = np.ones((4, 4))
print(o2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [41]:
arr1 = np.random.randn(10)
print(arr1)

arr2 = np.random.randint(10, 20, 5)
print(arr2)

arr3 = np.random.ranf(5)
print(arr3)



[ 0.25898171 -0.26125744 -1.80219671 -0.13290834 -1.52712586  1.24426311
 -0.06480251  0.30672089  0.4393959   0.98714871]
[10 10 17 19 16]
[0.31796115 0.07532656 0.3038985  0.2696829  0.90404719]


**References:**

Python for Data Analysis, 2nd Edition, McKinney (2017)